// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace DoubleTakeInventory.UnitTests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Add a test consignor
        /// </summary>
        public void NewTestConsignor()
        {
            #region Variable Declarations
            WinMenuItem uIAddConsignorMenuItem = this.UIConsignmentInventoryWindow.UIMenuStrip1MenuBar.UIConsignorMenuItem.UIAddConsignorMenuItem;
            WinEdit uITxtFirstNameEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtFirstNameWindow.UITxtFirstNameEdit;
            WinEdit uITxtLastNameEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtLastNameWindow.UITxtLastNameEdit;
            WinEdit uITxtAddressEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtAddressWindow.UITxtAddressEdit;
            WinEdit uITxtCityEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtCityWindow.UITxtCityEdit;
            WinEdit uITxtStateEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtStateWindow.UITxtStateEdit;
            WinEdit uITxtZipCodeEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UI_________Window.UITxtZipCodeEdit;
            WinEdit uITxtHomePhoneEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UI__________Window.UITxtHomePhoneEdit;
            WinEdit uITxtWorkPhoneEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UI__________Window1.UITxtWorkPhoneEdit;
            WinEdit uITxtCellPhoneEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UI__________Window2.UITxtCellPhoneEdit;
            WinEdit uITxtemailEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtemailWindow.UITxtemailEdit;
            WinEdit uITxtCommentsEdit = this.UIConsignmentInventoryWindow.UIConsignorWindow.UITxtCommentsWindow.UITxtCommentsEdit;
            WinButton uISaveButton = this.UIConsignmentInventoryWindow.UIConsignorWindow.UISaveWindow.UISaveButton;
            WinButton uINOButton = this.UINewConsignorWindow.UINOWindow.UINOButton;
            #endregion

            // Click 'Consignor' -> 'Add Consignor' menu item
            Mouse.Click(uIAddConsignorMenuItem, new Point(59, 13));

            // Type 'Test' in 'txtFirstName' text box
            uITxtFirstNameEdit.Text = this.NewTestConsignorParams.UITxtFirstNameEditText;

            // Type '{Tab}' in 'txtFirstName' text box
            Keyboard.SendKeys(uITxtFirstNameEdit, this.NewTestConsignorParams.UITxtFirstNameEditSendKeys, ModifierKeys.None);

            // Type 'Test' in 'txtLastName' text box
            uITxtLastNameEdit.Text = this.NewTestConsignorParams.UITxtLastNameEditText;

            // Type '{Tab}' in 'txtLastName' text box
            Keyboard.SendKeys(uITxtLastNameEdit, this.NewTestConsignorParams.UITxtLastNameEditSendKeys, ModifierKeys.None);

            // Type 'Test' in 'txtAddress' text box
            uITxtAddressEdit.Text = this.NewTestConsignorParams.UITxtAddressEditText;

            // Type '{Tab}' in 'txtAddress' text box
            Keyboard.SendKeys(uITxtAddressEdit, this.NewTestConsignorParams.UITxtAddressEditSendKeys, ModifierKeys.None);

            // Type 'Test' in 'txtCity' text box
            uITxtCityEdit.Text = this.NewTestConsignorParams.UITxtCityEditText;

            // Type '{Tab}' in 'txtCity' text box
            Keyboard.SendKeys(uITxtCityEdit, this.NewTestConsignorParams.UITxtCityEditSendKeys, ModifierKeys.None);

            // Type 'wa' in 'txtState' text box
            uITxtStateEdit.Text = this.NewTestConsignorParams.UITxtStateEditText;

            // Type '{Tab}' in 'txtState' text box
            Keyboard.SendKeys(uITxtStateEdit, this.NewTestConsignorParams.UITxtStateEditSendKeys, ModifierKeys.None);

            // Type '98027-____' in 'txtZipCode' text box
            uITxtZipCodeEdit.Text = this.NewTestConsignorParams.UITxtZipCodeEditText;

            // Type '{Tab}' in 'txtZipCode' text box
            Keyboard.SendKeys(uITxtZipCodeEdit, this.NewTestConsignorParams.UITxtZipCodeEditSendKeys, ModifierKeys.None);

            // Type '(425) 123-1234' in 'txtHomePhone' text box
            uITxtHomePhoneEdit.Text = this.NewTestConsignorParams.UITxtHomePhoneEditText;

            // Type '{NumPad5}{Tab}' in 'txtHomePhone' text box
            Keyboard.SendKeys(uITxtHomePhoneEdit, this.NewTestConsignorParams.UITxtHomePhoneEditSendKeys, ModifierKeys.None);

            // Type '(425) 123-1234' in 'txtWorkPhone' text box
            uITxtWorkPhoneEdit.Text = this.NewTestConsignorParams.UITxtWorkPhoneEditText;

            // Type '{NumPad5}{Tab}' in 'txtWorkPhone' text box
            Keyboard.SendKeys(uITxtWorkPhoneEdit, this.NewTestConsignorParams.UITxtWorkPhoneEditSendKeys, ModifierKeys.None);

            // Type '(425) 123-1234' in 'txtCellPhone' text box
            uITxtCellPhoneEdit.Text = this.NewTestConsignorParams.UITxtCellPhoneEditText;

            // Type '{NumPad5}{Tab}' in 'txtCellPhone' text box
            Keyboard.SendKeys(uITxtCellPhoneEdit, this.NewTestConsignorParams.UITxtCellPhoneEditSendKeys, ModifierKeys.None);

            // Type 'email@email.com' in 'txtemail' text box
            uITxtemailEdit.Text = this.NewTestConsignorParams.UITxtemailEditText;

            // Type 'test consignor' in 'txtComments' text box
            uITxtCommentsEdit.Text = this.NewTestConsignorParams.UITxtCommentsEditText;

            // Click 'Save' button
            Mouse.Click(uISaveButton, new Point(24, 27));

            // Click '&No' button
            Mouse.Click(uINOButton, new Point(55, 13));
        }
        
        #region Properties
        public virtual NewTestConsignorParams NewTestConsignorParams
        {
            get
            {
                if ((this.mNewTestConsignorParams == null))
                {
                    this.mNewTestConsignorParams = new NewTestConsignorParams();
                }
                return this.mNewTestConsignorParams;
            }
        }
        
        public UIConsignmentInventoryWindow UIConsignmentInventoryWindow
        {
            get
            {
                if ((this.mUIConsignmentInventoryWindow == null))
                {
                    this.mUIConsignmentInventoryWindow = new UIConsignmentInventoryWindow();
                }
                return this.mUIConsignmentInventoryWindow;
            }
        }
        
        public UINewConsignorWindow UINewConsignorWindow
        {
            get
            {
                if ((this.mUINewConsignorWindow == null))
                {
                    this.mUINewConsignorWindow = new UINewConsignorWindow();
                }
                return this.mUINewConsignorWindow;
            }
        }
        #endregion
        
        #region Fields
        private NewTestConsignorParams mNewTestConsignorParams;
        
        private UIConsignmentInventoryWindow mUIConsignmentInventoryWindow;
        
        private UINewConsignorWindow mUINewConsignorWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'NewTestConsignor'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class NewTestConsignorParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Test' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'txtFirstName' text box
        /// </summary>
        public string UITxtFirstNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Test' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'txtLastName' text box
        /// </summary>
        public string UITxtLastNameEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Test' in 'txtAddress' text box
        /// </summary>
        public string UITxtAddressEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'txtAddress' text box
        /// </summary>
        public string UITxtAddressEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Test' in 'txtCity' text box
        /// </summary>
        public string UITxtCityEditText = "Test";
        
        /// <summary>
        /// Type '{Tab}' in 'txtCity' text box
        /// </summary>
        public string UITxtCityEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'wa' in 'txtState' text box
        /// </summary>
        public string UITxtStateEditText = "wa";
        
        /// <summary>
        /// Type '{Tab}' in 'txtState' text box
        /// </summary>
        public string UITxtStateEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '98027-____' in 'txtZipCode' text box
        /// </summary>
        public string UITxtZipCodeEditText = "98027-____";
        
        /// <summary>
        /// Type '{Tab}' in 'txtZipCode' text box
        /// </summary>
        public string UITxtZipCodeEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '(425) 123-1234' in 'txtHomePhone' text box
        /// </summary>
        public string UITxtHomePhoneEditText = "(425) 123-1234";
        
        /// <summary>
        /// Type '{NumPad5}{Tab}' in 'txtHomePhone' text box
        /// </summary>
        public string UITxtHomePhoneEditSendKeys = "{NumPad5}{Tab}";
        
        /// <summary>
        /// Type '(425) 123-1234' in 'txtWorkPhone' text box
        /// </summary>
        public string UITxtWorkPhoneEditText = "(425) 123-1234";
        
        /// <summary>
        /// Type '{NumPad5}{Tab}' in 'txtWorkPhone' text box
        /// </summary>
        public string UITxtWorkPhoneEditSendKeys = "{NumPad5}{Tab}";
        
        /// <summary>
        /// Type '(425) 123-1234' in 'txtCellPhone' text box
        /// </summary>
        public string UITxtCellPhoneEditText = "(425) 123-1234";
        
        /// <summary>
        /// Type '{NumPad5}{Tab}' in 'txtCellPhone' text box
        /// </summary>
        public string UITxtCellPhoneEditSendKeys = "{NumPad5}{Tab}";
        
        /// <summary>
        /// Type 'email@email.com' in 'txtemail' text box
        /// </summary>
        public string UITxtemailEditText = "email@email.com";
        
        /// <summary>
        /// Type 'test consignor' in 'txtComments' text box
        /// </summary>
        public string UITxtCommentsEditText = "test consignor";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIConsignmentInventoryWindow : WinWindow
    {
        
        public UIConsignmentInventoryWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Consignment Inventory Management System";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public UIMenuStrip1MenuBar UIMenuStrip1MenuBar
        {
            get
            {
                if ((this.mUIMenuStrip1MenuBar == null))
                {
                    this.mUIMenuStrip1MenuBar = new UIMenuStrip1MenuBar(this);
                }
                return this.mUIMenuStrip1MenuBar;
            }
        }
        
        public UIConsignorWindow UIConsignorWindow
        {
            get
            {
                if ((this.mUIConsignorWindow == null))
                {
                    this.mUIConsignorWindow = new UIConsignorWindow(this);
                }
                return this.mUIConsignorWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMenuStrip1MenuBar mUIMenuStrip1MenuBar;
        
        private UIConsignorWindow mUIConsignorWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIMenuStrip1MenuBar : WinMenuBar
    {
        
        public UIMenuStrip1MenuBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenu.PropertyNames.Name] = "menuStrip1";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public UIConsignorMenuItem UIConsignorMenuItem
        {
            get
            {
                if ((this.mUIConsignorMenuItem == null))
                {
                    this.mUIConsignorMenuItem = new UIConsignorMenuItem(this);
                }
                return this.mUIConsignorMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private UIConsignorMenuItem mUIConsignorMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIConsignorMenuItem : WinMenuItem
    {
        
        public UIConsignorMenuItem(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinMenuItem.PropertyNames.Name] = "Consignor";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinMenuItem UIAddConsignorMenuItem
        {
            get
            {
                if ((this.mUIAddConsignorMenuItem == null))
                {
                    this.mUIAddConsignorMenuItem = new WinMenuItem(this);
                    #region Search Criteria
                    this.mUIAddConsignorMenuItem.SearchProperties[WinMenuItem.PropertyNames.Name] = "Add Consignor";
                    this.mUIAddConsignorMenuItem.SearchConfigurations.Add(SearchConfiguration.ExpandWhileSearching);
                    this.mUIAddConsignorMenuItem.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUIAddConsignorMenuItem;
            }
        }
        #endregion
        
        #region Fields
        private WinMenuItem mUIAddConsignorMenuItem;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIConsignorWindow : WinWindow
    {
        
        public UIConsignorWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "NewConsignor";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public UITxtFirstNameWindow UITxtFirstNameWindow
        {
            get
            {
                if ((this.mUITxtFirstNameWindow == null))
                {
                    this.mUITxtFirstNameWindow = new UITxtFirstNameWindow(this);
                }
                return this.mUITxtFirstNameWindow;
            }
        }
        
        public UITxtLastNameWindow UITxtLastNameWindow
        {
            get
            {
                if ((this.mUITxtLastNameWindow == null))
                {
                    this.mUITxtLastNameWindow = new UITxtLastNameWindow(this);
                }
                return this.mUITxtLastNameWindow;
            }
        }
        
        public UITxtAddressWindow UITxtAddressWindow
        {
            get
            {
                if ((this.mUITxtAddressWindow == null))
                {
                    this.mUITxtAddressWindow = new UITxtAddressWindow(this);
                }
                return this.mUITxtAddressWindow;
            }
        }
        
        public UITxtCityWindow UITxtCityWindow
        {
            get
            {
                if ((this.mUITxtCityWindow == null))
                {
                    this.mUITxtCityWindow = new UITxtCityWindow(this);
                }
                return this.mUITxtCityWindow;
            }
        }
        
        public UITxtStateWindow UITxtStateWindow
        {
            get
            {
                if ((this.mUITxtStateWindow == null))
                {
                    this.mUITxtStateWindow = new UITxtStateWindow(this);
                }
                return this.mUITxtStateWindow;
            }
        }
        
        public UI_________Window UI_________Window
        {
            get
            {
                if ((this.mUI_________Window == null))
                {
                    this.mUI_________Window = new UI_________Window(this);
                }
                return this.mUI_________Window;
            }
        }
        
        public UI__________Window UI__________Window
        {
            get
            {
                if ((this.mUI__________Window == null))
                {
                    this.mUI__________Window = new UI__________Window(this);
                }
                return this.mUI__________Window;
            }
        }
        
        public UI__________Window1 UI__________Window1
        {
            get
            {
                if ((this.mUI__________Window1 == null))
                {
                    this.mUI__________Window1 = new UI__________Window1(this);
                }
                return this.mUI__________Window1;
            }
        }
        
        public UI__________Window2 UI__________Window2
        {
            get
            {
                if ((this.mUI__________Window2 == null))
                {
                    this.mUI__________Window2 = new UI__________Window2(this);
                }
                return this.mUI__________Window2;
            }
        }
        
        public UITxtemailWindow UITxtemailWindow
        {
            get
            {
                if ((this.mUITxtemailWindow == null))
                {
                    this.mUITxtemailWindow = new UITxtemailWindow(this);
                }
                return this.mUITxtemailWindow;
            }
        }
        
        public UITxtCommentsWindow UITxtCommentsWindow
        {
            get
            {
                if ((this.mUITxtCommentsWindow == null))
                {
                    this.mUITxtCommentsWindow = new UITxtCommentsWindow(this);
                }
                return this.mUITxtCommentsWindow;
            }
        }
        
        public UISaveWindow UISaveWindow
        {
            get
            {
                if ((this.mUISaveWindow == null))
                {
                    this.mUISaveWindow = new UISaveWindow(this);
                }
                return this.mUISaveWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITxtFirstNameWindow mUITxtFirstNameWindow;
        
        private UITxtLastNameWindow mUITxtLastNameWindow;
        
        private UITxtAddressWindow mUITxtAddressWindow;
        
        private UITxtCityWindow mUITxtCityWindow;
        
        private UITxtStateWindow mUITxtStateWindow;
        
        private UI_________Window mUI_________Window;
        
        private UI__________Window mUI__________Window;
        
        private UI__________Window1 mUI__________Window1;
        
        private UI__________Window2 mUI__________Window2;
        
        private UITxtemailWindow mUITxtemailWindow;
        
        private UITxtCommentsWindow mUITxtCommentsWindow;
        
        private UISaveWindow mUISaveWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtFirstNameWindow : WinWindow
    {
        
        public UITxtFirstNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtFirstName";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtFirstNameEdit
        {
            get
            {
                if ((this.mUITxtFirstNameEdit == null))
                {
                    this.mUITxtFirstNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtFirstNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Consignor Name";
                    this.mUITxtFirstNameEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtFirstNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtFirstNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtLastNameWindow : WinWindow
    {
        
        public UITxtLastNameWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtLastName";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtLastNameEdit
        {
            get
            {
                if ((this.mUITxtLastNameEdit == null))
                {
                    this.mUITxtLastNameEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtLastNameEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Last Name";
                    this.mUITxtLastNameEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtLastNameEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtLastNameEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtAddressWindow : WinWindow
    {
        
        public UITxtAddressWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtAddress";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtAddressEdit
        {
            get
            {
                if ((this.mUITxtAddressEdit == null))
                {
                    this.mUITxtAddressEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtAddressEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtAddressEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtAddressEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtCityWindow : WinWindow
    {
        
        public UITxtCityWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCity";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCityEdit
        {
            get
            {
                if ((this.mUITxtCityEdit == null))
                {
                    this.mUITxtCityEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCityEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtCityEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCityEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtStateWindow : WinWindow
    {
        
        public UITxtStateWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtState";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtStateEdit
        {
            get
            {
                if ((this.mUITxtStateEdit == null))
                {
                    this.mUITxtStateEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtStateEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtStateEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtStateEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UI_________Window : WinWindow
    {
        
        public UI_________Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtZipCode";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtZipCodeEdit
        {
            get
            {
                if ((this.mUITxtZipCodeEdit == null))
                {
                    this.mUITxtZipCodeEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtZipCodeEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtZipCodeEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtZipCodeEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UI__________Window : WinWindow
    {
        
        public UI__________Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtHomePhone";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtHomePhoneEdit
        {
            get
            {
                if ((this.mUITxtHomePhoneEdit == null))
                {
                    this.mUITxtHomePhoneEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtHomePhoneEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Cell";
                    this.mUITxtHomePhoneEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtHomePhoneEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtHomePhoneEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UI__________Window1 : WinWindow
    {
        
        public UI__________Window1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtWorkPhone";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtWorkPhoneEdit
        {
            get
            {
                if ((this.mUITxtWorkPhoneEdit == null))
                {
                    this.mUITxtWorkPhoneEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtWorkPhoneEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtWorkPhoneEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtWorkPhoneEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UI__________Window2 : WinWindow
    {
        
        public UI__________Window2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtCellPhone";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCellPhoneEdit
        {
            get
            {
                if ((this.mUITxtCellPhoneEdit == null))
                {
                    this.mUITxtCellPhoneEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCellPhoneEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtCellPhoneEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCellPhoneEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtemailWindow : WinWindow
    {
        
        public UITxtemailWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtemail";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtemailEdit
        {
            get
            {
                if ((this.mUITxtemailEdit == null))
                {
                    this.mUITxtemailEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtemailEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtemailEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtemailEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UITxtCommentsWindow : WinWindow
    {
        
        public UITxtCommentsWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtComments";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtCommentsEdit
        {
            get
            {
                if ((this.mUITxtCommentsEdit == null))
                {
                    this.mUITxtCommentsEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtCommentsEdit.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUITxtCommentsEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtCommentsEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISaveWindow : WinWindow
    {
        
        public UISaveWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cmdSave";
            this.WindowTitles.Add("Consignment Inventory Management System");
            #endregion
        }
        
        #region Properties
        public WinButton UISaveButton
        {
            get
            {
                if ((this.mUISaveButton == null))
                {
                    this.mUISaveButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISaveButton.SearchProperties[WinButton.PropertyNames.Name] = "Save";
                    this.mUISaveButton.WindowTitles.Add("Consignment Inventory Management System");
                    #endregion
                }
                return this.mUISaveButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISaveButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UINewConsignorWindow : WinWindow
    {
        
        public UINewConsignorWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "New Consignor";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("New Consignor");
            #endregion
        }
        
        #region Properties
        public UINOWindow UINOWindow
        {
            get
            {
                if ((this.mUINOWindow == null))
                {
                    this.mUINOWindow = new UINOWindow(this);
                }
                return this.mUINOWindow;
            }
        }
        #endregion
        
        #region Fields
        private UINOWindow mUINOWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UINOWindow : WinWindow
    {
        
        public UINOWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "7";
            this.WindowTitles.Add("New Consignor");
            #endregion
        }
        
        #region Properties
        public WinButton UINOButton
        {
            get
            {
                if ((this.mUINOButton == null))
                {
                    this.mUINOButton = new WinButton(this);
                    #region Search Criteria
                    this.mUINOButton.SearchProperties[WinButton.PropertyNames.Name] = "No";
                    this.mUINOButton.WindowTitles.Add("New Consignor");
                    #endregion
                }
                return this.mUINOButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUINOButton;
        #endregion
    }
}
